In [14]:
import numpy as np
dd = np.array([[1.7582417582417582416, 0.87912087912087912086, 1.098901098901098901, 1.054945054945054945, 0.70329670329670329663, 0.65934065934065934062], [0.87912087912087912086, 1.6703296703296703295, 1.0109890109890109889, 0.83516483516483516477, 0.65934065934065934059, 0.79120879120879120875], [1.098901098901098901, 1.0109890109890109889, 2.10989010989010989, 1.2747252747252747252, 1.0549450549450549449, 0.8351648351648351648], [1.054945054945054945, 0.83516483516483516481, 1.2747252747252747252, 2.1098901098901098899, 1.0989010989010989009, 1.0109890109890109889], [0.70329670329670329668, 0.65934065934065934064, 1.054945054945054945, 1.098901098901098901, 1.7582417582417582416, 0.87912087912087912083], [0.65934065934065934064, 0.79120879120879120877, 0.83516483516483516482, 1.0109890109890109889, 0.87912087912087912079, 1.6703296703296703296]])
dd.shape
0.15*dd @ np.array([1,1,1,1,1,1])

array([0.92307692, 0.87692308, 1.10769231, 1.10769231, 0.92307692,
       0.87692308])

In [11]:
import networkx as nx

# Create an empty graph
G = nx.Graph()

# Add nodes and edges to your graph
G.add_nodes_from([1, 2, 3, 4, 5, 6])
G.add_edges_from([(1, 2), (1, 3), (1, 4), (2, 3), (2,6), (3,4), (3,5), (4,5), (4,6),(5,6)])

# Calculate the adjacency matrix
adj_matrix = nx.to_numpy_array(G)

# Print the adjacency matrix
print("Adjacency Matrix:")
print(adj_matrix)

Adjacency Matrix:
[[0. 1. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0. 1.]
 [1. 1. 0. 1. 1. 0.]
 [1. 0. 1. 0. 1. 1.]
 [0. 0. 1. 1. 0. 1.]
 [0. 1. 0. 1. 1. 0.]]


In [ ]:
betweenness_centrality = nx.betweenness_centrality(G)
print("Betweenness Centrality:")
print(betweenness_centrality)

closeness_centrality = nx.closeness_centrality(G)
print("Closeness Centrality:")
print(closeness_centrality)

# Nodes for which you want to calculate similarity
node_v3 = 3
node_v5 = 5

# Get the neighbors of node_v3 and node_v5
neighbors_v3 = set(G.neighbors(node_v3))
neighbors_v5 = set(G.neighbors(node_v5))

# Jaccard Similarity
jaccard_similarity = len(neighbors_v3.intersection(neighbors_v5)) / len(neighbors_v3.union(neighbors_v5))

# Cosine Similarity
cosine_similarity = len(neighbors_v3.intersection(neighbors_v5)) / (len(neighbors_v3) * len(neighbors_v5)) ** 0.5

print(f"Jaccard Similarity between v3 and v5: {jaccard_similarity:.4f}")
print(f"Cosine Similarity between v3 and v5: {cosine_similarity:.4f}")

# Choose a node for which you want to calculate the local clustering coefficient
node_of_interest = [1, 3, 5, 6]

for node in node_of_interest:
    # Calculate the local clustering coefficient for the chosen node
    local_clustering_coefficient = nx.clustering(G, node)

    print(f"Local Clustering Coefficient for Node {node}: {local_clustering_coefficient:.4f}")




# Create an empty graph
PrimsG = nx.Graph()

# Add nodes and edges to represent the ConnectWorld graph
PrimsG.add_nodes_from(['v1', 'v2', 'v3', 'v4', 'v5', 'v6'])
PrimsG.add_weighted_edges_from([('v1', 'v2', 6), ('v1', 'v3', 3), ('v1', 'v5', 4), ('v2', 'v3', 6),
                                ('v2', 'v4', 4), ('v2', 'v5', 5), ('v3', 'v5', 2), ('v4', 'v5', 7),
                                ('v4', 'v6', 6), ('v5', 'v6', 7)])

# Modify the graph to make 'v3' the first node
new_order = ['v3'] + [node for node in PrimsG.nodes() if node != 'v3']
PrimsG = PrimsG.subgraph(new_order).copy()

# Initialize the MST using Prim's algorithm
MST = nx.minimum_spanning_tree(PrimsG)

# Calculate cumulative weights
cumulative_weight = 0
steps = []

for u, v, w in MST.edges(data=True):
    cumulative_weight += w['weight']
    steps.append((u, v, cumulative_weight))

# Sort the steps by cumulative weight
steps.sort(key=lambda x: x[2])

# Print the steps
for step in steps:
    print(f"Chosen Edge: {step[0]} - {step[1]}, Cumulative Weight: {step[2]}")